from tkinter import *
screen=Tk()
screen.title("J Slider")
screen.geometry("800x700")
screen.configure(bg="White")
def function1():
    s1=s.get()
    label.config(text=s1)
s=Scale(screen, from_=1,to=1000 )
s.grid(row=0, column=2)
label=Label(screen)
label.grid(row=2, column=4)
b1=Button(screen, text="Display vertical", fg="White", bg="Purple", font=("Verdana", 20), command=function1)
b1.grid(row=3, column=0)
l1=Label(screen, text="Vertical Scale Value =", fg="Black", bg="White", font=("Verdana", 20))
l1.grid(row=2, column=3)
l2=Label(screen, text=".0", fg="Black", bg="White", font=("Verdana", 12))
l2.grid(row=2, column=5)
mainloop()