from tkinter import *
screen=Tk()
screen.title("Root Window")
screen.geometry("800x700")
screen.configure(bg="White")
l1=Label(screen, text="This Is The Root Window", fg="black", bg="White", font=("Verdana", 20))
l1.grid(row=0, column=0)
def Toplevel1():
    screen1=Tk()
    screen1.title("Toplevel1 window")
    screen1.geometry("600x500")
    screen.configure(bg="White")
    l2=Label(screen1, text="This is the Toplevel1 Window", fg="Black", bg="white", font=("Verdana", 20))
    l2.grid(row=0, column=0)
    b2=Button(screen1, text="open Toplevel2", fg="Black", bg="White", font=("Verdana", 20),command=Toplevel2)
    b2.grid(row=1, column=0)
    b3=Button(screen1, text="Exit", fg="Black", bg="White", font=("Verdana", 20), command=screen1.destroy)
    b3.grid(row=2, column=0)
def Toplevel2():
    screen2=Tk()
    screen2.title("Toplevel2")
    screen2.geometry("500x400")
    screen2.configure(bg="White")
    l3=Label(screen2, text="This Is The Toplevel2 Window", fg="Black", bg="White", font=("Verdana", 20))
    l3.grid(row=0, column=0)
    b4=Button(screen2, text="Exit", fg="black", bg="white", font=("Verdana", 20), command=screen2.destroy)
    b4.grid(row=1, column=0)
b1=Button(screen, text="Open Toplevel1", fg="Black", bg="White", font=("Verdana", 20), command=Toplevel1)
b1.grid(row=1, column=2)
mainloop()