from tkinter import *
screen=Tk()
screen.title("user")
screen.geometry("200x300")
screen.configure(bg="White")
l=Listbox(screen, width=10)
l.grid()
l.insert(END, "user 1")
l.insert(END, "user 2")
l.insert(END, "user 3")
l.insert(END, "user 4")
l.insert(END, "user 5")
l.insert(END, "user 6")
l.insert(END, "user 7")
l.insert(END, "user 8")
l.insert(END, "user 9")
l.insert(END, "user 10")
l.insert(END, "user 11")
l.insert(END, "user 12")
l.insert(END, "user 13")
l.insert(END, "user 14")
l.insert(END, "user 15")
l.insert(END, "user 16")
l.insert(END, "user 17")
l.insert(END, "user 18")
l.insert(END, "user 19")
l.insert(END, "user 20")
l.insert(END, "user 21")
l.insert(END, "user 22")
l.insert(END, "user 23")
l.insert(END, "user 24")
l.insert(END, "user 25")
l.insert(END, "user 26")
l.insert(END, "user 27")
l.insert(END, "user 28")
l.insert(END, "user 29")
l.insert(END, "user 30")
l.insert(END, "user 31")
l.insert(END, "user 32")
l.insert(END, "user 33")
l.insert(END, "user 34")
l.insert(END, "user 35")
l.insert(END, "user 36")
l.insert(END, "user 37")
l.insert(END, "user 38")
l.insert(END, "user 39")
l.insert(END, "user 40")
l.insert(END, "user 41")
l.insert(END, "user 42")
l.insert(END, "user 43")
l.insert(END, "user 44")
l.insert(END, "user 45")
l.insert(END, "user 46")
s=Scrollbar(screen, command=l.yview)
l.configure(yscrollcommand=s.set)
l.pack(side=RIGHT, fill=BOTH, expand=TRUE)
mainloop()